language: ruby
rvm:
- 2.3.0
sudo: required
services:
- redis-server
cache: bundler
deploy:
  provider: rubygems
  api_key:
    secure: PR4iJ3IN4CBR4Y4YTc3W5o7i+w6TuCtE/O2z5X3jyaHWvB+7CQrHqP22n2ALLJNZgeKBgkfEBBJ8ZWPtEK1j4GQw7Hdy1Ct0tFnhtYpCaFVAaLnx0fiN7vOT349ZYVSZ3DzviOmyjy31HjxjWNqLmLxOkoxPpSv5TpK2WDjr4dxiv2ufNm+W+6RNBdCR/Pd9Au+Z4Wzl2rbOmbj2zNXTgFHS7U16owLuJqpK/lR9iQZhPAHG/hDOOYmZBXXJKkpqwC7WTA3zhYQj3/dPDmZKU+mHhqRuOKoy3ylyYK3TIwIgc8GuaDUY2Ekk3j99kGC7xKn6pghyxjP+z2WITeXGX9OKBkH13K1+uXXUhZnfAWUlaDiUwOIa+mfYpjbw64CZr25zabljZhAgZhnluuImp4h7NwlFyqu9TjugPToIjmKXRJASBJudmoEY+Qpq/6adWsY9mD61RVQ0z7USNIKNUr0T8fVYe7CzW2qgScUKcYN9i/Mp88AZkX+GZ+5NUyau94nRt9+z1vK9pGg30FGVr9nrXb17dBVRXttH4tjHbdOxJ9YSWTQc8cX6qBfxmavEyjzJNiBuJBuDfIAC8gayT/mxueCmX0sDoG9WyYpf6p6P8uQ+fhR8s7R5jdQdRz1vO9IE8osjNl0k908Cs2DsSBLnD9E+tnUTMt51Khx2k0U=
  gem: lita-jenkins-notifier
  on:
    tags: true
    repo: cyberkov/lita-jenkins-notifier
