language: ruby
rvm:
- 2.3
sudo: required
services:
- redis-server
cache: bundler
deploy:
  provider: rubygems
  api_key:
    secure: gfAAvQ2UYgIkdNK8Ctwa7Tj8xZhTJmEb3n6xW0akAtyloxQh9RNXxb59nkMsRm2EL3nEwCozU7/YdE2v9Khvihg8toZN6JpkReMV44jSI23nj8rT9/eJ9M/vlsmIC9uEM0ch9P2o64PjQU6jCtYsE2SetjQ436uCzQAPzN3qBZynV9ZraegsELRMa+zhndeXIIryOSKAzYUrn/UrlOrvw/JmTSZrd+UBgq43HAjhaLAWV9Rp4KKdx0Z49F878ZOyVT+sB8Y7gjK9KV89G4A+KS7dKefL/y1sGHA4Ga3hZPMRS2xpwSz4sPuFvEcvqXJkcANue2auH0podbb0SmXWP1hgXKYGVSx4/5lEzcT2t9FRCYIO3Q3ZceEONoxT04ccFxWwv1UP1EarhByaocwFXQNLgRpvYtjjmm5Sq+GIpyED6FtLVyOEKe03IdGVBq9+dkOWdoBm20kMEIc1uPsK+k33vulQC1kvi19IMdRpgD/Hz3GA+W9yikc+Vy+6/YPGSaEGlcQH1wdBPqj+XtcPJGA1ocYL8+8G8vnz4IsdY7zljrS0Ngodu+j/424tV5HnVMtQoTQxdhLcC4upcWeq6bs4NKOEw+Vt+OZ4aDizZV2wXSJjyTofje3LvBueFSBq3gF5QcYYWUo2mmuxxRjyFyxUmBSeAJ/8zke/b9+Ifzo=
  gem: lita-jenkins-notifier
  on:
    tags: true
    repo: cyberkov/lita-jenkins-notifier
